SmartSchoolSystem/SmartSchoolSystem/Models/TimeTableViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartSchoolSystem.Models
{
    public class TimeTableViewModel
    {
        public static List<TimeTableViewModel> lst = new List<TimeTableViewModel>();

        public int id { get; set; }

        public string subject { get; set; }

        public string day { get; set; }
    }
}

SmartSchoolSystem/SmartSchoolSystem/Controllers/TimeTableController.cs
using SmartSchoolSystem.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartSchoolSystem.Controllers
{
    public class TimeTableController : Controller
    {
        // GET: TimeTable
        public ActionResult Index()
        {

            TimeTableIndexViewModels.indextimetable.Clear();
            DB37Entities db = new DB37Entities();
            List<string> classlist = new List<string>();
            string temp;

            foreach (Classtbl c in db.Classtbls)
            {
                temp = c.Section;
                classlist.Add(temp);
            }

            ViewBag.Options = classlist;
            ViewBag.classname = "";
            return View(TimeTableIndexViewModels.indextimetable);
        }
        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            TimeTableIndexViewModels.indextimetable.Clear();
            DB37Entities db = new DB37Entities();
            List<string> classlist = new List<string>();
            string temp;

            foreach (Classtbl c in db.Classtbls)
            {
                temp = c.Section;
                classlist.Add(temp);
            }

            ViewBag.Options = classlist;

            string classname = form["Classlist"].ToString();
            ViewBag.classname = classname;
            int classid = db.Classtbls.Where(t => t.Section.Equals(classname)).FirstOrDefault().Id;
            foreach(TimeTabletbl t in db.TimeTabletbls)
            {
                if(t.ClassId == classid && t.WeeksDay == "Monday")
                {
                    TimeTableIndexViewModels a = new TimeTableIndexViewModels();
                    a.subjectname = db.Subjectstbls.Where(a1 => a1.Id == t.SubjectId).FirstOrDefault().Name;
                    a.dayname = t.WeeksDay;
                    a.time = t.LectureTime.ToString()+" AM";
                    TimeTableIndexViewModels.indextimetable.Add(a);
                }
            }
            foreach (TimeTabletbl t in db.TimeTabletbls)
            {
                if (t.ClassId == classid && t.WeeksDay == "Tuesday")
                {
                    TimeTableIndexViewModels a = new TimeTableIndexViewModels();
                    a.subjectname = db.Subjectstbls.Where(a1 => a1.Id == t.SubjectId).FirstOrDefault().Name;
                    a.dayname = t.WeeksDay;
                    a.time = t.LectureTime.ToString() + " AM";
                    TimeTableIndexViewModels.indextimetable.Add(a);
                }
            }
            foreach (TimeTabletbl t in db.TimeTabletbls)
            {
                if (t.ClassId == classid && t.WeeksDay == "Wednesday")
                {
                    TimeTableIndexViewModels a = new TimeTableIndexViewModels();
                    a.subjectname = db.Subjectstbls.Where(a1 => a1.Id == t.SubjectId).FirstOrDefault().Name;
                    a.dayname = t.WeeksDay;
                    a.time = t.LectureTime.ToString() + " AM";
                    TimeTableIndexViewModels.indextimetable.Add(a);
                }
            }
            foreach (TimeTabletbl t in db.TimeTabletbls)
            {
                if (t.ClassId == classid && t.WeeksDay == "Thursday")
                {
                    TimeTableIndexViewModels a = new TimeTableIndexViewModels();
                    a.subjectname = db.Subjectstbls.Where(a1 => a1.Id == t.SubjectId).FirstOrDefault().Name;
                    a.dayname = t.WeeksDay;
                    a.time = t.LectureTime.ToString() + " AM";
                    TimeTableIndexViewModels.indextimetable.Add(a);
                }
            }
            foreach (TimeTabletbl t in db.TimeTabletbls)
            {
                if (t.ClassId == classid && t.WeeksDay == "Friday")
                {
                    TimeTableIndexViewModels a = new TimeTableIndexViewModels();
                    a.subjectname = db.Subjectstbls.Where(a1 => a1.Id == t.SubjectId).FirstOrDefault().Name;
                    a.dayname = t.WeeksDay;
                    a.time = t.LectureTime.ToString() + " AM";
                    TimeTableIndexViewModels.indextimetable.Add(a);
                }
            }
            return View(TimeTableIndexViewModels.indextimetable);
        }
        // GET: TimeTable/Details/5
        public ActionResult redirecttodetailedtimetable(string classname)
        {
            if(HelperClass.account == null || HelperClass.account == "" || HelperClass.accountid == -1)
            {
                RedirectToAction("Index", "Home");
            }
            TimeTableDetailedViewModels.classname = classname;
            TimeTableDetailedViewModels.timetablelist.Clear();
            DB37Entities db = new DB37Entities();
            int classid = db.Classtbls.Where(t => t.Section == classname).FirstOrDefault().Id;
            TimeTableController t1 = new TimeTableController();
            t1.AddTimeTableObj("Monday", classid);
            t1.AddTimeTableObj("Tuesday", classid);
            t1.AddTimeTableObj("Wednesday", classid);
            t1.AddTimeTableObj("Thursday", classid);
            t1.AddTimeTableObj("Friday", classid);
            return Json(new { r = "success" });


        }

        public ActionResult DetailedTimeTable()
        {
            if (HelperClass.account == null || HelperClass.account == "" || HelperClass.accountid == -1)
            {
                RedirectToAction("Index", "Home");
            }
            ViewBag.classname = TimeTableDetailedViewModels.classname;
            return View(TimeTableDetailedViewModels.timetablelist);
        }
        public void AddTimeTableObj(string dayname, int classid)
        {
            DB37Entities db = new DB37Entities();
            int subjectid;
            TimeTableDetailedViewModels timetableobj = new TimeTableDetailedViewModels();
            timetableobj.dayname = dayname;
            string timename1 = "08:00:00 AM";
            CultureInfo culture1 = new CultureInfo("en-US");
            DateTime tempDate1 = Convert.ToDateTime("01/01/0001 " + timename1, culture1);
            if (db.TimeTabletbls.Any(t => t.WeeksDay == timetableobj.dayname && t.LectureTime.ToString() == tempDate1.TimeOfDay.ToString() && t.ClassId == classid))
            {
                subjectid = db.TimeTabletbls.Where(t => t.WeeksDay == timetableobj.dayname && t.LectureTime.ToString() == tempDate1.TimeOfDay.ToString()).FirstOrDefault().SubjectId;
                timetableobj.lecture1 = db.Subjectstbls.Where(t => t.Id == subjectid).FirstOrDefault().Name;
            }
            else
            {
                timetableobj.lecture1 = null;
            }
            string timename2 = "09:00:00 AM";
            CultureInfo culture2 = new CultureInfo("en-US");
            DateTime tempDate2 = Convert.ToDateTime("01/01/0001 " + timename2, culture2);
            if (db.TimeTabletbls.Any(t => t.WeeksDay == timetableobj.dayname && t.LectureTime.ToString() == tempDate2.TimeOfDay.ToString() && t.ClassId == classid))
            {
                subjectid = db.TimeTabletbls.Where(t => t.WeeksDay == timetableobj.dayname && t.LectureTime.ToString() == tempDate2.TimeOfDay.ToString()).FirstOrDefault().SubjectId;
                timetableobj.lecture2 = db.Subjectstbls.Where(t => t.Id == subjectid).FirstOrDefault().Name;
            }
            else
            {
                timetableobj.lecture2 = null;
            }
            string timename3 = "10:00:00 AM";
            CultureInfo culture3 = new CultureInfo("en-US");
            DateTime tempDate3 = Convert.ToDateTime("01/01/0001 " + timename3, culture3);
            if (db.TimeTabletbls.Any(t => t.WeeksDay == timetableobj.dayname && t.LectureTime.ToString() == tempDate3.TimeOfDay.ToString() && t.ClassId == classid))
            {
                subjectid = db.TimeTabletbls.Where(t => t.WeeksDay == timetableobj.dayname && t.LectureTime.ToString() == tempDate3.TimeOfDay.ToString()).FirstOrDefault().SubjectId;
                timetableobj.lecture3 = db.Subjectstbls.Where(t => t.Id == subjectid).FirstOrDefault().Name;
            }
            else
            {
                timetableobj.lecture3 = null;
            }
            string timename4 = "11:00:00 AM";
            CultureInfo culture4 = new CultureInfo("en-US");
            DateTime tempDate4 = Convert.ToDateTime("01/01/0001 " + timename4, culture4);
            if (db.TimeTabletbls.Any(t => t.WeeksDay == timetableobj.dayname && t.LectureTime.ToString() == tempDate4.TimeOfDay.ToString() && t.ClassId == classid))
            {
                subjectid = db.TimeTabletbls.Where(t => t.WeeksDay == timetableobj.dayname && t.LectureTime.ToString() == tempDate4.TimeOfDay.ToString()).FirstOrDefault().SubjectId;
                timetableobj.lecture4 = db.Subjectstbls.Where(t => t.Id == subjectid).FirstOrDefault().Name;
            }
            else
            {
                timetableobj.lecture4 = null;
            }
            string timename5 = "12:00:00 AM";
            CultureInfo culture5 = new CultureInfo("en-US");
            DateTime tempDate5 = Convert.ToDateTime("01/01/0001 " + timename5, culture5);
            if (db.TimeTabletbls.Any(t => t.WeeksDay == timetableobj.dayname && t.LectureTime.ToString() == tempDate5.TimeOfDay.ToString() && t.ClassId == classid))
            {
                subjectid = db.TimeTabletbls.Where(t => t.WeeksDay == timetableobj.dayname && t.LectureTime.ToString() == tempDate5.TimeOfDay.ToString()).FirstOrDefault().SubjectId;
                timetableobj.lecture5 = db.Subjectstbls.Where(t => t.Id == subjectid).FirstOrDefault().Name;
            }
            else
            {
                timetableobj.lecture5 = null;
            }
            TimeTableDetailedViewModels.timetablelist.Add(timetableobj);

        }
        public ActionResult Details(int id)
        {

SmartSchoolSystem/SmartSchoolSystem/Views/TimeTable/Create.cshtml
@model SmartSchoolSystem.Models.TimeTableViewModel

@{
    ViewBag.Title = "Create";
}

<div style="padding-top:40px;">
    <div style="position:relative; width: 40%; height: 400px; border: 1px solid; margin: auto;padding-top:20px; padding-left: 00px; border-radius: 10px; box-shadow: 5px 10px 50px; background-color: #F9F9F9;">


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4 style="position: relative; left: 38%;">Create Time Table</h4>
                
                    <div style="padding-left:20px;">
                        
                        <div class="form-group">
                            <label for="Classlist" class="control-label col-md-2">Class: </label>
                            <div class="col-md-10">
                                <select id="Classlist" name="Classlist" class="form-control">
                                    @foreach (var o in ViewBag.Options)
                                    {
                                        <option value="@o.ToString()">@o.ToString()</option>
                                    }
                                </select>
                            </div>
                        </div>




                        <div class="form-group">
                            <label for="subjectList" class="control-label col-md-2">Subject: </label>
                            <div class="col-md-10">
                                <select id="subjectList" name="subjectList" class="form-control">
                                    @foreach (var o in new SelectList(""))
                                    {
                                        <option value="@o.ToString()">@o.ToString()</option>
                                    }
                                </select>
                            </div>
                        </div>
                       


                        <div class="form-group">
                            <label for="daylist" class="control-label col-md-2">Day: </label>
                            <div class="col-md-10">
                                <select id="daylist" name="daylist" class="form-control">
                                    @foreach (var o in ViewBag.Days)
                                    {
                                        <option value="@o.ToString()">@o.ToString()</option>
                                    }
                                </select>
                            </div>
                        </div>






                        <div class="form-group">
                            <label for="timelist" class="control-label col-md-2">Time:</label>
                            <div class="col-md-10">
                                <select id="timelist" name="timelist" class="form-control">
                                    @foreach (var o in ViewBag.Time)
                                    {
                                        <option value="@o.ToString()">@o.ToString()</option>
                                    }
                                </select>
                            </div>
                        </div>
                        </div>
                        <div class="text-danger" style="padding-left:40px">
                            @ViewBag.warn
                        </div>
                        
                        <div class="form-group">
                            <div style="position: relative; left: 48%;">
                                <button type="submit" class="btn btn-default" style="background-color:black; border-color:black; color:white;">Add</button>
                            </div>
                        </div>
                       
                
            </div>
            
        }
        </div>
    </div>



        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script>
            $(document).ready(function () {
                $("#Classlist").change(function () {
                    $.get("/TimeTable/UpdateSubjects", { classname: $("#Classlist").find(":selected").text() }, function (data) {
                        $("#subjectList").empty();
                        $.each(data, function (index, row) {
                            $("#subjectList").append("<option>" + row + "</option>")
                        });
                    });
                })
            });
        </script>

        @*
            @section Scripts {
                <script type="text/javascript">
                    $(document).ready(function () {
                        $("#Classlist").change(function () {
                            updatesubject();
                        });

                        function updatesub() {
                            $.ajax({
                                type: "POST",
                                url: 'http://localhost:50566/TimeTable/UpdateSubjects',
                                data: { input: $('#Classlist').val() },
                                contentType: "application/json; charset=utf-8",
                                dataType: "json",

                            });
                        }

                        updatesubject()
                        {
                            updatesub();
                        }
                    });
                </script>
            }
        *@

SmartSchoolSystem/SmartSchoolSystem/Views/TimeTable/DetailedTimeTable.cshtml
@model IEnumerable<SmartSchoolSystem.Models.TimeTableDetailedViewModels>

@{
    ViewBag.Title = "DetailedTimeTable";
}

<h2  style="padding-left:600px;">Time Table</h2>
<br />
<br />
<h3 style="padding-left:600px;">Class Name: @ViewBag.Classname</h3>
<div style="padding-left:200px;">
    <table class="table" style="border: 5px solid #000000; border-radius: 5px;align-self:center; width: 80%; height: auto;">
        <tr>
            <th>
                Day
            </th>
            <th>
                08:00:00 AM
            </th>
            <th>
                09:00:00 AM
            </th>
            <th>
                10:00:00 AM
            </th>
            <th>
                11:00:00 AM
            </th>
            <th>
            12:00:00 PM
            </th>

        </tr>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td style="font-weight:bold;">
                        @Html.DisplayFor(modelItem => item.dayname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.lecture1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.lecture2)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.lecture3)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.lecture4)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.lecture5)
                    </td>

                </tr>
            }
        }
    </table>
</div>

SmartSchoolSystem/SmartSchoolSystem/Views/TimeTable/Index.cshtml
@model IEnumerable<SmartSchoolSystem.Models.TimeTableIndexViewModels>

@{
    ViewBag.Title = "Index";
}
<style>
    .button
    {
        background-color:black; 
        border-color:black; 
        color:white;

    }
</style>

<h2 style="text-align:center;">Time Table Index Page</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    if (HelperClass.account == "Admin")
    {
<p style="padding-left:200px">
    <button style="background-color:black;">
    @Html.ActionLink("Add New Time Table Entry", "Create", "TimeTable",new { @class = "button" })
</button>
</p>
    }
<div style="padding-left:150px;">
    <label>Class: </label> &nbsp;
    <select id="Classlist" name="Classlist">

        @foreach (var o in ViewBag.Options)
        {
            <option value="@o.ToString()">@o.ToString()</option>
        }
    </select>
</div>
 if (HelperClass.account == "Admin")
 {
<div style="align-self:center; text-align:center;padding-bottom:30px;">
    <input type="submit" style="background-color:black; border-color:black; align-self:center; color:white;" value="Show Time Table" class="btn btn-default" />
</div>
 }
<div style="align-self:center; text-align:center;padding-bottom:30px;">
    <input type="button" name="timetable" id="timetable" style="background-color:black; border-color:black; align-self:center; color:white;" value="Show Time Table" class="btn btn-default" />
</div>
    if (HelperClass.account == "Admin")
    {
<h4 style="text-align:center;">@ViewBag.classname</h4>
<div style= "padding-left : 200px;">

    <table class="table"style="border: 5px solid #000000; border-radius: 5px;align-self:center; width: 90%; height: auto;">
        <tr>
            <th>
                
                   Day
                

            </th>
            <th>
                Subject Name

               
            </th>
            <th>
                Time
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    
                    @Html.DisplayFor(modelItem => item.dayname)
                        
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.subjectname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.time)
                </td>
                <td>
                   @if (HelperClass.account == "Admin")
                   {
                       <div  >
                           <button class="button">                    
                               @Html.ActionLink("Delete", "Delete", new { subjectname = item.subjectname, classname = ViewBag.classname, dayname = item.dayname, time = item.time }, new { @class = "button" })
                               </button>
                   </div>
                   }
                </td>
            </tr>
        }

    </table>
    </div>
    }
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>

    $("#timetable").click(function()
    {
        gototimetable();
    })
    /*$(document).ready(function () {
        $("#timetable").click(function () {
            //$.post("/TimeTable/redirecttodetailedtimetable", {classname: $("#Classlist").find(":selected").text()})

            var url = 'http://localhost:50566/TimeTable/redirecttodetailedtimetable';
            var data = {
                classname: $("#Classlist").find(":selected").text()
            };
            $.getJSON(url, classname, function (status) {
                if (status === 200) {
                    window.location.href = "http://localhost:50566/TimeTable/DetailedTimeTable";
                }
            })
           
        });
       
    });*/
    function gototimetable()
    {
        debugger;
        event.preventDefault();
        var $url = '/TimeTable/redirecttodetailedtimetable';
        $.ajax({
            url: $url,
            type: 'POST',
            datatype: 'json',
            data: jQuery.param({
                classname: $("#Classlist").find(":selected").text()
            }),
            success: function(r)
            {
                window.location.href = '/TimeTable/DetailedTimeTable'
            }
        })
    }
</script>